# Generated by Django 5.2.7 on 2025-10-29 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('estimated_gdp', models.BigIntegerField(null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
