# Generated by Django 5.2.7 on 2025-10-22 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.TextField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=1000)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
